export const designCopy = {
  en: {
    eyebrow: 'ANCIENT WISDOM, A FRESH PERSPECTIVE', title: ['Your stars.', 'Your story.', 'A clearer tomorrow.'],
    intro: 'Discover the patterns written in your birth chart. Thoughtful Vedic astrology to help you understand yourself and move forward with intention.',
    primary: 'Create my free Kundli', secondary: 'Explore my Rashifal', free: 'Free birth chart', signup: 'No sign-up needed', wheel: 'A UNIVERSE OF POSSIBILITIES', wheelSub: 'Your journey begins with you.',
    strip: ['Your birth. Your unique chart.', 'Rooted in Vedic tradition', 'Made for everyday life'],
    zodiacLabel: 'A MOMENT FOR YOURSELF', zodiacTitle: 'What do your stars say?', zodiacDesc: 'Choose your Rashi to explore your daily horoscope.', zodiacHelp: 'Not sure of your Rashi?', find: 'Find it in your Kundli',
    serviceLabel: 'EXPLORE YOUR PATH', serviceTitle: 'A little guidance. A new perspective.', serviceDesc: 'Start with curiosity. Explore the parts of life that matter to you.',
    cards: [['Your birth chart, decoded', 'Explore your planetary placements, Nakshatra, and Dasha periods in a personal Vedic birth chart.', 'Create a free Kundli'], ['Connection, beyond chemistry', 'Explore compatibility through the traditional Ashtakoot system of Kundli matching.', 'Explore compatibility'], ['Make space for what’s next', 'Find a fresh perspective on career, relationships, and personal growth with detailed reports.', 'Discover your reports']],
    dailyLabel: 'IN RHYTHM WITH THE DAY', dailyTitle: 'Make today a little more intentional.', dailyDesc: 'Explore the Panchang, the Vedic calendar of daily celestial rhythms. A small ritual for a more mindful day.', dailyLink: 'Explore today’s Panchang', location: 'New Delhi, India · IST', loading: 'Finding today’s celestial details…', unavailable: 'Explore the full Panchang to choose your date and city.', tithi: 'Tithi', nakshatra: 'Nakshatra', yoga: 'Yoga',
    howLabel: 'SIMPLE, PERSONAL, YOURS', howTitle: 'Your story starts here.', steps: [['Tell us your beginnings', 'Enter your birth date, time, and place.'], ['Discover your cosmic blueprint', 'Explore your chart and planetary placements.'], ['Find your own meaning', 'Reflect on insights at your own pace.']],
    faqLabel: 'A FEW THINGS TO KNOW', faqTitle: 'Curiosity is a good place to start.', faqs: [['Is my birth chart really free?', 'Yes. You can generate your basic Kundli and explore planetary placements without signing up. Optional detailed reports and other paid features are priced separately.'], ['What details do I need?', 'Your date of birth, exact birth time, and birth city. A more precise birth time helps calculate the Ascendant and house placements.'], ['Is this based on Vedic astrology?', 'Yes. Charts use the sidereal zodiac with Lahiri Ayanamsa. Planetary positions are calculated astronomically, with AI used for written interpretations.'], ['Can astrology predict my future?', 'Astrology is a tradition for reflection and spiritual guidance, not a guarantee of future events. Your choices matter. It is not a substitute for professional advice.']],
    ctaLabel: 'A NEW WAY TO SEE YOURSELF', ctaTitle: 'The next chapter is yours.', ctaDesc: 'Begin with your birth chart. Let curiosity lead the way.', footerDesc: 'Ancient Vedic wisdom, thoughtfully reimagined for everyday life.', explore: 'Explore', discover: 'Discover', connect: 'Stay connected', journal: 'The journal', feedback: 'Share feedback',
  },
  hi: {
    eyebrow: 'प्राचीन ज्ञान, एक नया नज़रिया', title: ['आपके सितारे।', 'आपकी कहानी।', 'एक स्पष्ट कल।'], intro: 'अपनी जन्म कुंडली के माध्यम से खुद को समझें। वैदिक ज्योतिष के साथ जीवन को एक नए नज़रिए से देखें।', primary: 'मेरी निःशुल्क कुंडली बनाएँ', secondary: 'मेरा राशिफल देखें', free: 'निःशुल्क जन्म कुंडली', signup: 'साइन-अप ज़रूरी नहीं', wheel: 'संभावनाओं का एक ब्रह्मांड', wheelSub: 'आपकी यात्रा, आपसे शुरू होती है।', strip: ['आपका जन्म, आपकी अनूठी कुंडली', 'वैदिक परंपरा पर आधारित', 'रोज़मर्रा के जीवन के लिए'], zodiacLabel: 'खुद के लिए एक पल', zodiacTitle: 'आपके सितारे क्या कहते हैं?', zodiacDesc: 'आज का राशिफल जानने के लिए अपनी राशि चुनें।', zodiacHelp: 'अपनी राशि नहीं जानते?', find: 'कुंडली में जानें', serviceLabel: 'अपना रास्ता खोजें', serviceTitle: 'थोड़ा मार्गदर्शन, एक नया नज़रिया।', serviceDesc: 'जीवन के उन पहलुओं को समझें जो आपके लिए मायने रखते हैं।', cards: [['अपनी जन्म कुंडली समझें', 'ग्रहों की स्थिति, नक्षत्र और दशा के साथ अपनी वैदिक जन्म कुंडली देखें।', 'निःशुल्क कुंडली बनाएँ'], ['रिश्तों को गहराई से समझें', 'पारंपरिक अष्टकूट प्रणाली से कुंडली मिलान और अनुकूलता जानें।', 'कुंडली मिलान करें'], ['आने वाले कल को समझें', 'करियर, रिश्तों और व्यक्तिगत विकास के लिए विस्तृत रिपोर्ट देखें।', 'अपनी रिपोर्ट देखें']], dailyLabel: 'दिन की लय के साथ', dailyTitle: 'आज को थोड़ा और सार्थक बनाएँ।', dailyDesc: 'वैदिक पंचांग के माध्यम से आज की तिथि, नक्षत्र और योग जानें।', dailyLink: 'आज का पंचांग देखें', location: 'नई दिल्ली, भारत · IST', loading: 'आज का पंचांग लोड हो रहा है…', unavailable: 'अपनी तारीख और शहर चुनने के लिए पंचांग देखें।', tithi: 'तिथि', nakshatra: 'नक्षत्र', yoga: 'योग', howLabel: 'सरल, व्यक्तिगत, आपका', howTitle: 'आपकी कहानी यहाँ शुरू होती है।', steps: [['अपने जन्म का विवरण दें', 'जन्म तिथि, समय और स्थान दर्ज करें।'], ['अपनी कुंडली जानें', 'ग्रहों की स्थिति और कुंडली को समझें।'], ['अपना अर्थ खोजें', 'अपनी गति से विचार करें और सीखें।']], faqLabel: 'कुछ ज़रूरी बातें', faqTitle: 'जिज्ञासा से शुरुआत करें।', faqs: [['क्या जन्म कुंडली निःशुल्क है?', 'हाँ। मूल कुंडली और ग्रहों की स्थिति बिना साइन-अप के देख सकते हैं। विस्तृत रिपोर्ट जैसे वैकल्पिक फीचर्स का शुल्क अलग है।'], ['कौन-सी जानकारी चाहिए?', 'जन्म तिथि, सटीक जन्म समय और जन्म शहर। सही समय से लग्न और भावों की गणना बेहतर होती है।'], ['क्या यह वैदिक ज्योतिष पर आधारित है?', 'हाँ। लाहिड़ी अयनांश के साथ निरयण राशि चक्र का उपयोग होता है। ग्रहों की गणना खगोलीय विधि से और लिखित व्याख्या AI से होती है।'], ['क्या भविष्य निश्चित बताया जा सकता है?', 'ज्योतिष आत्मचिंतन और आध्यात्मिक मार्गदर्शन की परंपरा है, भविष्य की गारंटी नहीं। यह पेशेवर सलाह का विकल्प नहीं है।']], ctaLabel: 'खुद को देखने का नया नज़रिया', ctaTitle: 'अगला अध्याय आपका है।', ctaDesc: 'अपनी जन्म कुंडली से शुरुआत करें।', footerDesc: 'रोज़मर्रा के जीवन के लिए प्राचीन वैदिक ज्ञान।', explore: 'खोजें', discover: 'और जानें', connect: 'जुड़े रहें', journal: 'लेख', feedback: 'अपनी राय दें',
  },
  mr: {
    eyebrow: 'प्राचीन ज्ञान, एक नवा दृष्टिकोन', title: ['तुमचे तारे.', 'तुमची गोष्ट.', 'उद्याची नवी दिशा.'], intro: 'तुमच्या जन्मकुंडलीतून स्वतःला समजून घ्या. वैदिक ज्योतिषाच्या साथीने आयुष्याकडे नव्या दृष्टिकोनातून पाहा.', primary: 'माझी मोफत कुंडली बनवा', secondary: 'माझे राशिभविष्य पाहा', free: 'मोफत जन्मकुंडली', signup: 'नोंदणी आवश्यक नाही', wheel: 'शक्यतांचे एक विश्व', wheelSub: 'तुमचा प्रवास, तुमच्यापासून सुरू होतो.', strip: ['तुमचा जन्म, तुमची खास कुंडली', 'वैदिक परंपरेवर आधारित', 'रोजच्या आयुष्यासाठी'], zodiacLabel: 'स्वतःसाठी एक क्षण', zodiacTitle: 'तुमचे तारे काय सांगतात?', zodiacDesc: 'आजचे राशिभविष्य जाणून घेण्यासाठी तुमची रास निवडा.', zodiacHelp: 'तुमची रास माहीत नाही?', find: 'कुंडलीतून जाणून घ्या', serviceLabel: 'तुमची वाट शोधा', serviceTitle: 'थोडे मार्गदर्शन, एक नवी दृष्टी.', serviceDesc: 'तुमच्यासाठी महत्त्वाच्या आयुष्याच्या पैलूंना समजून घ्या.', cards: [['तुमची जन्मकुंडली समजून घ्या', 'ग्रहस्थिती, नक्षत्र आणि दशांसह तुमची वैदिक जन्मकुंडली पाहा.', 'मोफत कुंडली बनवा'], ['नात्यांचा नवा अर्थ', 'पारंपरिक अष्टकूट पद्धतीने कुंडली जुळवणी आणि अनुकूलता जाणून घ्या.', 'कुंडली जुळवा'], ['पुढील वाटचालीसाठी', 'करिअर, नातेसंबंध आणि वैयक्तिक विकासासाठी सविस्तर अहवाल पाहा.', 'तुमचे अहवाल पाहा']], dailyLabel: 'दिवसाच्या लयीत', dailyTitle: 'आजचा दिवस अधिक अर्थपूर्ण करा.', dailyDesc: 'वैदिक पंचांगातून आजची तिथी, नक्षत्र आणि योग जाणून घ्या.', dailyLink: 'आजचे पंचांग पाहा', location: 'नवी दिल्ली, भारत · IST', loading: 'आजचे पंचांग लोड होत आहे…', unavailable: 'तारीख आणि शहर निवडण्यासाठी संपूर्ण पंचांग पाहा.', tithi: 'तिथी', nakshatra: 'नक्षत्र', yoga: 'योग', howLabel: 'सोपे, वैयक्तिक, तुमचे', howTitle: 'तुमची गोष्ट इथून सुरू होते.', steps: [['जन्माची माहिती द्या', 'जन्मतारीख, वेळ आणि ठिकाण नोंदवा.'], ['तुमची कुंडली जाणून घ्या', 'ग्रहस्थिती आणि कुंडली समजून घ्या.'], ['तुमचा अर्थ शोधा', 'तुमच्या गतीने विचार करा आणि शिका.']], faqLabel: 'काही महत्त्वाच्या गोष्टी', faqTitle: 'जिज्ञासेपासून सुरुवात करा.', faqs: [['जन्मकुंडली खरंच मोफत आहे का?', 'होय. मूलभूत कुंडली आणि ग्रहस्थिती नोंदणीशिवाय पाहू शकता. सविस्तर अहवालांसारख्या ऐच्छिक सुविधांसाठी वेगळे शुल्क आहे.'], ['कोणती माहिती लागते?', 'जन्मतारीख, अचूक जन्मवेळ आणि जन्मशहर. अचूक वेळेमुळे लग्न आणि भावांची गणना अधिक योग्य होते.'], ['हे वैदिक ज्योतिषावर आधारित आहे का?', 'होय. लाहिरी अयनांशासह निरयन राशिचक्र वापरले जाते. ग्रहांची गणना खगोलशास्त्रीय पद्धतीने आणि लिखित विवेचन AI द्वारे केले जाते.'], ['भविष्य निश्चित सांगता येते का?', 'ज्योतिष ही आत्मचिंतन आणि आध्यात्मिक मार्गदर्शनाची परंपरा आहे, भविष्याची हमी नाही. हा व्यावसायिक सल्ल्याचा पर्याय नाही.']], ctaLabel: 'स्वतःकडे पाहण्याची नवी दृष्टी', ctaTitle: 'पुढचा अध्याय तुमचा आहे.', ctaDesc: 'तुमच्या जन्मकुंडलीपासून सुरुवात करा.', footerDesc: 'रोजच्या आयुष्यासाठी प्राचीन वैदिक ज्ञान.', explore: 'शोधा', discover: 'आणखी जाणून घ्या', connect: 'जोडलेले राहा', journal: 'लेख', feedback: 'अभिप्राय द्या',
  },
};
